version: '3.1'
services:
  proxy:
    build: proxy/
    ports: 
      - '80:80'
      - '443:443'
  jenkins:
    build: jenkins/
    ports: 
      - '8080:8080'
  nexus:
    build: nexus/
    ports: 
      - '8081:8081'