version: '3.4'
services:
  proxy:
    build: proxy/
    ports: 
      - '80:80'
      - '443:443'
  jenkins:
    build: jenkins/
    ports: 
      - '8080:8080'
      - '50000:50000'
    volumes:
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home

  nexus:
    build: nexus/
    ports: 
      - '8081:8081'
    volumes:
      - type: volume
        source: nexus-data
        target: /nexus-data
volumes:
  nexus-data:
  jenkins-data: